language: scala

script:
  - sbt +kamon-spring/test
  - sbt +kamon-spring-auto/test
scala:
   - 2.12.6
jdk:
   - oraclejdk8
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
sudo: false
